server:
  port: 8002


spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/tensquare_recruit?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
