server:
  port: 8008
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/tensquare_user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  application:
    name: tensquare_user

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:6868/eureka/

jwt:
  config:
    key: itcast

